apiVersion: v1
kind: ServiceAccount
metadata:
  name: guestbook-sa
  namespace: kapp-packages
  annotations:
    kapp.k14s.io/change-group: "packageinstall-setup"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: guestbook-cluster-admin
  annotations:
    kapp.k14s.io/change-group: "packageinstall-setup"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: guestbook-cluster-admin
  annotations:
    kapp.k14s.io/change-group: "packageinstall-setup"
subjects:
- kind: ServiceAccount
  name: guestbook-sa
  namespace: kapp-packages
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: guestbook-cluster-admin
