apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: guestbook
  namespace: kapp-packages
spec:
  serviceAccountName: guestbook-sa
  packageRef:
    refName: guestbook.test.carvel.dev
    versionSelection:
      constraints: 1.0.0
  values:
  - secretRef:
      name: guestbook-values
---
apiVersion: v1
kind: Secret
metadata:
  name: guestbook-values
  namespace: kapp-packages
stringData:
  values.yml: |
    redis_port: 6379
    katacoda: false
    push_images: false
    push_images_repo: docker.io/dkalinin
    namespace: guestbook
